### ISSUE TITLE
Avoid massive documents

### ISSUE THREAD

**Issue by OmgImAlexis** [chocolate-neko/tsumeki#1]
As it seems you're still learning I figured I'd point this out before you run into the issue.

https://github.com/chocolate-neko/tsumeki/blob/d204a4d967d6bbed983d71e9ee9c327984144c76/src/db.ts#L118

Since you're storing every user in the guild document you'll end up hitting issues if the bot is added to very large servers. Instead you should be storing a document per user and the settings for the user in that guild should be saved on that document.

Global settings across all guilds can be added to the top level of the user too.
```ts
const user = {
    userId: 00000000000,
    this_is_a_global_setting: false,
    guilds: [
        {
            guildId: 00000000000,
            banned: false
        }
    }
}
```

Another option is to have the user document contain a guilds object.

```ts
const user = {
    userId: 00000000000,
    guilds: {
        00000000000: {
            banned: false
        }
    }
}
```

**Comment by chocolate-neko** [comment]
Big thanks to @OmgImAlexis for raising this issue! I wouldn't have caught this otherwise
